import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="bg-gray-200 px-5">
        <main className="bg-white max-w-5xl px-5 min-h-[100dvh]">{children}</main>
        <Toaster
          position="bottom-right"
          toastOptions={{
            duration: 10000,
          }}
        />
      </body>
    </html>
  );
}
